### ISSUE TITLE
имплементировать 3 пальца на гриппер

### ISSUE THREAD

**Issue by AyaMech** [janeoa/ALARIS-Hand#9]
1) установить 3 пальца
2) заставить двигаться вокруг базы (вместе и раздельно)
3) заставить сжиматься и разжиматься пальцы

**Comment by janeoa** [comment]
Рахмет за поддержку с гриппером

у меня есть дубликат данной борды в гите от гриппера
https://github.com/janeoa/ALARIS-Gripper/projects/1

закрываю эту борду
